config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'blog', to: 'pages#blog', as: :blog
  get 'contact', to: 'pages#contact', as: :contact
  get 'faq', to: 'pages#faq', as: :faq
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def blog
  end

  def contact
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SPIRITWELL</title>
    <%= favicon_link_tag asset_path('spr_spiritwell_icon.png') %>
    <script src="https://kit.fontawesome.com/b4cf8f7e15.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <!-- Kappy was here 2020 - Signed Kappy -->
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/blog.html.erb
<div class="main-container">
  <img alt="spiritwell" class="spiritwell-header">
  <h1 class="text text--large">BLOG</h1>
  <p class="text">Coming soon...</p>
  <p class="text">For now, feel free to follow me on <a href="https://twitter.com/daviddchen" target="_blank" rel="noopener noreferrer" class="text text--link">Twitter</a>!</p>
  <img alt="kappy-following-gif" class="follow-gif">
</div>

app/views/pages/contact.html.erb
<div class="main-container">
  <img alt="spiritwell" class="spiritwell-header">
  <h1 class="text text--large">CONTACT</h1>
  <!-- <img alt="frog-mail-gif" class="frog-mail-gif"> -->
  <%= image_tag('frogmail2.png', class: "frog-mail-gif", alt: "frog-mail-gif", data: { 'play-url' => image_path('frogmail2.gif'), 'pause-url' => image_path('frogmail2.png') }) %>
  <p class="text">Make sure to read the <%= link_to "FAQ", faq_path, class: "text text--link"%> before sending any enquiries!</p>
  <p class="text">Your questions are likely to have already been answered there.</p>
  <p class="text">Otherwise… please send any enquiries to:</p>
  <p class="text text--email">spiritwellgame@gmail.com</p>
  <p class="text">… or feel free to reach out to me on <a href="https://twitter.com/daviddchen" target="_blank" rel="noopener noreferrer" class="text text--link">Twitter</a>. My DMs are open.</p>
  <p class="text text--margin-bottom">I’ll get back to you as soon as I can!</p>
</div>

app/views/pages/faq.html.erb
<div class="main-container">
  <img alt="spiritwell" class="spiritwell-header">
  <h1 class="text text--large">FAQ</h1>
  <p class="text text--small">(furiously asked questions)</p>
  <p class="text text--left-align text--underline">~ GENERAL ~</p>
  <p class="text text--left-align">Q: What’s a SPIRITWELL?</p>
  <p class="text text--left-align">A: Woah, straight to the fundamental question, aye? Why don’t you find out for yourself… by playing the DEMO. (Huh, what do you mean there’s no DEMO?) For real, though, check back soon™!</p>
  <br>
  <p class="text text--left-align">Q: Who’s making SPIRITWELL?</p>
  <p class="text text--left-align">A: It’s-a me, David! Find me on <a href="https://twitter.com/daviddchen" target="_blank" rel="noopener noreferrer" class="text text--link">Twitter</a>! (and asleep, anywhere)</p>
  <br>
  <p class="text text--left-align">Q: What’s under Kappy’s…</p>
  <p class="text text--left-align">A: Hey, mate, that’s a little too far.</p>
  <br>
  <p class="text text--left-align">Q: NICE.</p>
  <p class="text text--left-align">A: Thanks!</p>
  <br>
  <p class="text text--left-align text--underline">~ MAKING SPIRITWELL ~</p>
  <p class="text text--left-align">Q: What tools do you use to make the game?</p>
  <p class="text text--left-align">A: I use Game Maker Studio 2 for the game, FL Studio for the music, and Aseprite and MSPaint for the graphics. I also use food for the human.</p>
  <br>
  <p class="text text--left-align">Q: Can I help?</p>
  <p class="text text--left-align">A: Please send me your energy so I can make a giant SPIRITBOM-, uh, SPIRITWELL!</p>
  <br>
  <p class="text text--left-align text--underline">~ MISCELLANEOUS ~</p>
  <p class="text text--left-align">Q: How long are Butters’ legs?</p>
  <p class="text text--left-align">A: </p>
  <img alt="butter-long-legs" class="butter-long-legs">
  <p class="text">(To be honest, even I don’t know.</p>
  <p class="text">They could actually be longer…</p>
  <p class="text">its true power is shrouded in darkness.)</p>
</div>

app/views/pages/home.html.erb
<div class="main-container">
  <img alt="spiritwell" class="spiritwell-header">
  <p class="text">SPIRITWELL is an RPG about a lost child who falls down a well into a world of spirits…</p>
  <p class="text">Now, he must find his way home…</p>
  <p class="text">Journey through the Spiritwell.</p>
  <p class="text">Make friends. Make enemies.</p>
  <p class="text">… but try not to lose your way…</p>
  <br>
  <p class="text">( SPIRITWELL is currently in development for PC. Thanks for stopping by so early! )</p>
  <p class="text">(( Demo coming Q2 2020! ))</p>
  <div class="main-container__home-screens">
    <img alt="spiritwell-screenshot-0" class="main-container__home-screen main-container__home-screen--0">
    <img alt="spiritwell-screenshot-1" class="main-container__home-screen main-container__home-screen--1">
  </div>
  <p class="text">Story-rich and character driven experience, filled with personality.</p>
  <div class="main-container__home-screens">
    <img alt="spiritwell-screenshot-2" class="main-container__home-screen main-container__home-screen--2">
    <img alt="spiritwell-screenshot-3" class="main-container__home-screen main-container__home-screen--3">
  </div>
  <p class="text">SPIRITWELL is an RPG about the little things.</p>
  <p class="text">The absurd, the joyful, the heartrending, the frivolous…</p>
  <br>
  <p class="text">The forgotten moments we shared.</p>
  <br>
  <img alt="kappy-wave" class="kappy-wave">
  <p class="text text--small">* Thanks for stopping by!</p>
  <div class="home-blank"></div>
  <p class="text text--small">You've gone too far, go back!</p>
  <img alt="kappy-fall" class="kappy-fall">
</div>

app/views/shared/_footer.html.erb
<div class="footer"></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(root_path)%>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(blog_path)%>">
        <%= link_to "Blog", blog_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(contact_path)%>">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(faq_path)%>">
        <%= link_to "FAQ", faq_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/daviddchen" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact"><i class="fas fa-envelope"></i></a>
      </li>
    </ul>
  </div>
</nav>